### ISSUE TITLE
Wikidocs 페이지는 삭제됐나요?

### ISSUE THREAD

**Issue by hyunsungkim** [sharebook-kr/book-vivado-hls#1]
얼마 전까지 Wikidocs에 올라와있던 Xilinx Vivado HLS 페이지는 삭제된건가요?

**Comment by brayden-jo** [comment]
비공개 처리를 했는데 보는 분이 계셨군요.

**Comment by brayden-jo** [comment]
다시 공개로 변경했습니다. 일하면서 적다보니 너무 reference 형태로 글이 써진듯해서 좀 정리좀 하고 공개하려고 했었습니다.

**Comment by hyunsungkim** [comment]
감사합니다!
